Repository ClassRoom-Project/ClassRoom-Project, pull requests merged in 2024-04, with the labels that each got.

#52 [Feat]- 메인 페이지 기능구현 #26
  package.json
  postcss.config.js
  src/api/supabase/fetchClassInfo.ts
  src/app/api/supabase/fetchClassInfo.ts
  src/app/main/page.tsx
  src/components/main/BestClass.tsx
  src/components/main/ClassCard.tsx
  src/components/main/D1Class.tsx
  src/components/main/LatestClass.tsx
  src/store/ClassInfoStore.ts
  src/types/reactSlick.ts
  yarn.lock
Labels: enhancement

#56 [Feat] - 마이페이지 (수강생) : 내가 예약한 클래스 보기
  .gitignore
  package.json
  public/mainImage.png
  public/plusImage.PNG
  src/api/supabase/fetchClassInfo.ts
  src/app/api/mypage/my-class-api.ts
  src/app/api/mypage/user-api.ts
  src/app/api/supabase/fetchClassInfo.ts
  src/app/api/supabase/fetchMyClasses.ts
  src/app/layout.tsx
  src/app/mypage/page.tsx
  src/app/register/page.tsx
  src/components/common/UserLayout.tsx
  src/components/main/BestClass.tsx
  src/components/main/D1Class.tsx
  src/components/main/LatestClass.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/student/MyReservedClass.tsx
  src/components/mypage/teacher/MyClass.tsx
  src/components/register/Address.tsx
  src/components/register/Calendar.tsx
  src/components/register/Category.tsx
  src/components/register/CategoryDropdown.tsx
  src/components/register/ClassTypeDiff.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/TimeSelect.tsx
  src/components/register/TotalTime.tsx
  yarn.lock
Labels: enhancement

#57 [Feat] - 마이페이지 프로필 수정하기
  .gitignore
  src/app/api/mypage/my-class-api.ts
  src/app/api/mypage/user-api.ts
  src/app/api/supabase/fetchClassInfo.ts
  src/app/api/user-api.ts
  src/app/mypage/page.tsx
  src/components/main/BestClass.tsx
  src/components/main/D1Class.tsx
  src/components/main/LatestClass.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/teacher/EditTeacherInfo.tsx
  src/components/mypage/teacher/MyClass.tsx
  src/types/class.ts
  src/types/user.ts
Labels: enhancement

#58 [Feat] - 예약하기 페이지 부가 기능 구현 #44
  package.json
  src/app/api/supabase/fetchClassInfo.ts
  src/app/reserve/[reservationId]/page.tsx
  src/app/reserve/page.tsx
  src/components/main/D1Class.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReserveButton.tsx
  src/store/reserveClassStore.ts
  src/types/class.ts
  src/types/date.ts
  yarn.lock
Labels: enhancement

#64 [Refactor] - 마이페이지 내가 예약한 클래스 리팩토링
  src/app/api/supabase/fetchMyClasses.ts
  src/app/mypage/page.tsx
  src/app/register/page.tsx
  src/components/mypage/student/MyReservedClass.tsx
  src/types/register.ts
Labels: documentation

#67 [Feat] - 예약하기 페이지 부가 기능 구현(2) #59
  src/app/api/reserve/fetchClassInfo.ts
  src/app/api/reserve/fetchReserveInfo.ts
  src/app/api/reserve/fetchReservedUserIds.ts
  src/app/api/reserve/submitReservation.ts
  src/app/api/reserve/updateReservedUserList.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/reserve/[reservationId]/page.tsx
  src/app/reserve/page.tsx
  src/components/common/bars/UserLayout.tsx
  src/components/main/BestClass.tsx
  src/components/main/D1Class.tsx
  src/components/main/DeadlineClass.tsx
  src/components/main/LatestClass.tsx
  src/components/reserve/CurrentReserveQuantity.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReserveButton.tsx
  src/components/reserve/day-picker.css
  src/types/class.ts
  tailwind.config.ts
Labels: enhancement

#71 [Feat] - 클래스 등록 페이지 기능 구현
  src/app/api/mypage/fetchMyClasses.ts
  src/app/layout.tsx
  src/app/register/page.tsx
  src/components/register/Address.tsx
  src/components/register/Calendar.tsx
  src/components/register/Category.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassName.tsx
  src/components/register/ClassTitle.tsx
  src/components/register/ClassTypeDiff.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/Personnel.tsx
  src/components/register/Price.tsx
  src/components/register/TimeSelect.tsx
  src/components/register/TotalTime.tsx
  src/store/RegisterStore.ts
  src/types/register.ts
  tailwind.config.ts
Labels: documentation

#75 [Fix,Refactor] - 리뷰 코드 수정 및 리팩토링 #74
  src/app/(clrm)/layout.tsx
  src/app/(clrm)/main/page.tsx
  src/app/(clrm)/page.tsx
  src/app/api/mainpage/getClassAllInfo.ts
  src/app/hello/(loginRoot)/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/bars/Category.tsx
  src/components/common/bars/Header.tsx
  src/components/common/bars/SideBar.tsx
  src/components/common/bars/categories/SearchClass.tsx
Labels: enhancement

#78 [Feat] - 마이페이지 (수강생) : 내가 쓴 댓글(후기) 보기 #19
  .gitignore
  src/app/(clrm)/mypage/page.tsx
  src/app/api/mypage/my-class-api.ts
  src/app/api/mypage/my-comments-api.ts
  src/app/api/mypage/user-api.ts
  src/components/common/bars/SideBar.tsx
  src/components/common/mypage/buttons.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/EditProfileImage.tsx
  src/components/mypage/student/MyCommentItem.tsx
  src/components/mypage/student/MyComments.tsx
  src/components/mypage/student/StudentMyPageTab.tsx
  src/components/mypage/teacher/EditTeacherInfo.tsx
  src/components/mypage/teacher/MyClass.tsx
  src/components/mypage/teacher/TeacherMyPageTab.tsx
  src/types/class.ts
  src/types/comments.ts
  src/types/user.ts
  tailwind.config.ts
Labels: enhancement

#89 [Feat] - 클래스 등록 페이지 기능 구현
  package.json
  src/app/(clrm)/layout.tsx
  src/app/api/mypage/fetchMyClasses.ts
  src/components/register/Address.tsx
  src/components/register/Category.tsx
  src/components/register/ClassTitle.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/TimeSelect.tsx
  src/components/register/TotalTime.tsx
  src/types/register.ts
  yarn.lock
Labels: enhancement

#101 [Feat] 예약하기 부가 기능 구현(3) #53
  src/app/(clrm)/reserve/page.tsx
  src/app/api/reserve/checkIsReserved.tsx
  src/app/api/reserve/fetchReservedUserIds.ts
  src/app/api/reserve/submitReservation.ts
  src/components/reserve/CheckAlreadyReserved.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/PriceCalculator.tsx
  src/components/reserve/ReserveButton.tsx
Labels: enhancement

#113 [Feat] - 세션별 남은자리 체크하기(2) - 달력에 일자별 예약 가능 시간 보여주기 #108
  src/app/(clrm)/reserve/page.tsx
  src/app/api/reserve/fetchReserveClassInfo.ts
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/types/class.ts
  src/types/date.ts
Labels: enhancement

#121 [Refact] - 클래스 등록 페이지 리팩토링
  public/plus.PNG
  public/plusImage.jpg
  src/app/(clrm)/layout.tsx
  src/app/(clrm)/register/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/mypage/user-api.ts
  src/app/hello/(loginRoot)/layout.tsx
  src/components/common/bars/Header.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/teacher/EditTeacherInfo.tsx
  src/components/register/Address.tsx
  src/components/register/Category.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassTitle.tsx
  src/components/register/ClassTypeDiff.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/Personnel.tsx
  src/components/register/Price.tsx
  src/components/register/TimeSelect.tsx
  src/components/register/TotalTime.tsx
  src/store/RegisterScheduleStore.ts
  src/store/RegisterStore.ts
  src/types/register.ts
Labels: documentation, enhancement

#133 [Style] - 예약(결제)완료 페이지 스타일링 #130
  src/app/(clrm)/reserve/[reservationCompleted]/page.tsx
  src/app/(clrm)/reserve/page.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/ReserveButton.tsx
  src/components/reserve/ReserveUserInfo.tsx
  src/components/reserve/reservationComplete/NavigationButtons.tsx
  tailwind.config.ts
Labels: enhancement

#145 [Feat] - 남은자리 로직 수정 #144
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/reserve/countReservationsByTimeId.ts
  src/app/api/reserve/fetchReservationDetails.ts
  src/app/api/reserve/sumReserveQuantityByTimeId.ts
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReserveButton.tsx
  src/hooks/useReserve/useFetchReservationDetail.ts
  src/store/reserveClassStore.ts
  src/types/reserve.ts
Labels: enhancement

#150 [Feat] - 알림 기능 구현
  public/plusImage.jpg
  src/app/(clrm)/register/Completed/[id]/page.tsx
  src/app/(clrm)/register/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/reserve/insertNotice.ts
  src/components/common/Notification.tsx
  src/components/common/bars/Header.tsx
  src/components/register/Address.tsx
  src/components/register/Category.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassDiff.tsx
  src/components/register/ClassTitle.tsx
  src/components/register/ClassTypeDiff.tsx
  src/components/register/HashTag.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/Personnel.tsx
  src/components/register/Price.tsx
  src/components/register/TimeSelect.tsx
  src/components/register/TotalTime.tsx
  src/types/notice.ts
  src/types/register.ts
Labels: enhancement

#158 [Fix] 입력, 유효성 검사 수정
  src/components/common/bars/Header.tsx
  src/components/common/bars/SideBar.tsx
  src/components/common/bars/categories/SearchClass.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/TimeSelect.tsx
  src/components/register/TotalTime.tsx
  src/store/registerStore.ts
  src/types/register.ts
Labels: documentation

#162 [Fix] - 버그 수정
  .gitignore
  next.config.mjs
  package.json
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/payment/route.ts
  src/app/api/wish/wishApi.ts
  src/app/layout.tsx
  src/components/classDetail/ClassDetailBtn.tsx
  src/components/classDetail/CreateComments.tsx
  src/components/classDetail/DetailWishButton.tsx
  src/components/common/Toastify.tsx
  src/components/common/bars/SideBar.tsx
  src/components/listpage/ListPageWishButton.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/student/AddTeacherInfo.tsx
  src/components/mypage/student/MyCommentItem.tsx
  src/components/mypage/teacher/EditTeacherInfo.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/ReserveButton.tsx
  src/hooks/useWish/mutateWish.ts
  yarn.lock
Labels: enhancement

#166 [style] - 알림창 위치 변경
  src/components/common/Notification.tsx
Labels: documentation

#178 [Refactor] - 예약 기능 리팩토링 #168
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/MessageBoxs.tsx
  src/app/(clrm)/reserve/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/listpage/classInfoForList.ts
  src/app/api/payment/route.ts
  src/app/api/reserve/fetchReserveClassInfo.ts
  src/app/api/wish/wishApi.ts
  src/components/classDetail/DetailWishButton.tsx
  src/components/common/WishIcon.tsx
  src/components/listpage/ListPageWishButton.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReservationScheduler.tsx
  src/components/reserve/ReserveButton.tsx
  src/components/reserve/ReserveInfo.tsx
  src/components/reserve/ReserveUserInfo.tsx
  src/components/reserve/SetQuantityAndPay.tsx
  src/components/reserve/reservationComplete/NavigationButtons.tsx
  src/constants/QueryKeys.ts
  src/hooks/useWish/mutateWish.ts
  src/hooks/useWish/useWish.ts
  src/hooks/useWish/useWishQueries.ts
  src/store/reserveClassStore.ts
  src/types/class.ts
  src/types/reserve.ts
  tailwind.config.ts
Labels: enhancement

#183 [Feat] - 세부기능 구현 및 수정
  package.json
  src/app/(clrm)/register/page.tsx
  src/components/common/Notification.tsx
  src/components/common/Toastify.tsx
  src/components/mypage/MyPageBtn.tsx
  src/components/register/Category.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassTitleType.tsx
  src/components/register/CreateBtn.tsx
  src/components/register/HashTag.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/SelectTime.tsx
  src/store/registerStore.ts
  src/types/register.ts
  yarn.lock
Labels: documentation, enhancement

#191 Feature/99
  postcss.config.js
  src/app/(clrm)/fail/[loginUserId]/page.tsx
  src/app/(clrm)/reserve/fail/page.tsx
  src/app/globals.css
  src/components/chatRooms/ChatButton.tsx
  src/components/common/bars/Header.tsx
  src/components/payments/PaymentFailPage.tsx
  src/components/payments/PaymentPage.tsx
Labels: enhancement

#194 [Feat] - Quill 텍스트에디터 기능 구현
  src/components/common/Notification.tsx
  src/components/common/Toastify.tsx
  src/components/common/bars/categories/SearchClass.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassTitleType.tsx
  src/components/register/HashTag.tsx
  src/components/register/SelectTime.tsx
Labels: documentation, enhancement

#197 [Style] - 예약페이지 반응형 디자인 구현
  src/app/(clrm)/reserve/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/listpage/classInfoForList.ts
  src/app/api/payment/route.ts
  src/app/api/reserve/fetchReserveClassInfo.ts
  src/app/api/reserve/insertNewReservation.ts
  src/app/api/reserve/sumReserveQuantityByTimeId.ts
  src/app/api/reserve/updateReservationCounts.ts
  src/app/api/wish/wishApi.ts
  src/app/layout.tsx
  src/components/common/BackButton.tsx
  src/components/listpage/ListPageWishButton.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReserveButton.tsx
  src/components/reserve/ReserveUserInfo.tsx
  src/components/reserve/SelectedDate.tsx
  src/components/reserve/day-picker.css
  src/components/reserve/reservationComplete/NavigationButtons.tsx
  src/types/class.ts
  src/types/reserve.ts
  tailwind.config.ts
Labels: enhancement

#200 [Style]
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/ChatMessages.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/ChatPreview.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/MessageBoxs.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/MessagesPage.tsx
  src/app/hello/(loginRoot)/layout.tsx
  src/assets/images/failIcon.gif
  src/components/chatRooms/ChatButton.tsx
  src/components/common/bars/SideBar.tsx
  src/components/mypage/MyPageBtn.tsx
  src/components/payments/PaymentFailPage.tsx
  src/components/register/CreateBtn.tsx
  src/hooks/useChatRoom/useNewChatRoom.tsx
Labels: documentation

#205 [style] 카테고리 css 수정
  src/app/(clrm)/(mypage)/myClassStudentList/page.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/ChatImageModal.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/ChatPreview.tsx
  src/app/api/chatRooms/getChatRooms.ts
  src/app/layout.tsx
  src/components/listpage/CategoryBtns.tsx
Labels: enhancement

#210 [Style,Fix] 캐러셀 수정,헤더 사이드바 css,카테고리 로직 변경 #196
  package.json
  src/app/(clrm)/list/detail/[id]/page.tsx
  src/app/(clrm)/list/page.tsx
  src/app/(clrm)/main/page.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/ChatPreview.tsx
  src/app/api/listpage/classInfoForList.ts
  src/components/classDetail/ClassDetailLeft.tsx
  src/components/classDetail/ClassDetailRight.tsx
  src/components/classDetail/ClassInfos.tsx
  src/components/classDetail/CommentsCard.tsx
  src/components/classDetail/CreateComments.tsx
  src/components/classDetail/ShowComments.tsx
  src/components/common/bars/Header.tsx
  src/components/common/bars/categories/SearchClass.tsx
  src/components/listpage/CategoryBtns.tsx
  src/components/listpage/ClassList.tsx
  src/components/listpage/SearchFilter.tsx
  src/components/login/LoginState.tsx
  src/components/main/Banner.tsx
  src/components/main/BestClass.tsx
  src/components/main/ClassCard.tsx
  src/components/main/DeadlineClass.tsx
  src/components/main/LatestClass.tsx
  yarn.lock
Labels: enhancement

#212 [Feat] - 세부기능 구현 및 수정
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/ChatPreview.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/MessageBoxs.tsx
  src/app/(clrm)/register/completedPage/[id]/page.tsx
  src/app/(clrm)/register/page.tsx
  src/app/(clrm)/register/registerEditPage/[id]/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/reserve/insertNotice.ts
  src/components/classDetail/ClassDetailLeft.tsx
  src/components/classDetail/CommentsCard.tsx
  src/components/common/Notification.tsx
  src/components/common/Toastify.tsx
  src/components/common/bars/Header.tsx
  src/components/main/Banner.tsx
  src/components/main/ClassCard.tsx
  src/components/mypage/EditProfileImage.tsx
  src/components/mypage/teacher/MyClass.tsx
  src/components/mypage/teacher/MyClassStudentList.tsx
  src/components/register/Address.tsx
  src/components/register/Category.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassDiff.tsx
  src/components/register/ClassTitleType.tsx
  src/components/register/HashTag.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/Price.tsx
  src/components/register/SelectTime.tsx
  src/components/register/TotalTime.tsx
  src/types/editClass.ts
Labels: documentation, enhancement

#217 [Feat] - 카테고리 평일/주말 필터링
  src/app/(clrm)/reserve/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/listpage/classInfoForList.ts
  src/components/common/bars/SideBar.tsx
  src/components/common/bars/categories/SearchClass.tsx
  src/components/listpage/SearchFilter.tsx
  src/components/main/ClassCard.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReserveUserInfo.tsx
  src/store/classFilterStore.ts
  src/types/class.ts
  tailwind.config.ts
Labels: enhancement

#225 [style] - 디테일 페이지 css, 기타 작업
  src/app/(clrm)/list/detail/[id]/page.tsx
  src/app/(clrm)/main/page.tsx
  src/app/api/classdetail/detailComment.ts
  src/assets/images/clroom_no_img_purple.png
  src/assets/images/clroom_no_img_white.png
  src/components/classDetail/ClassDetailBtn.tsx
  src/components/classDetail/ClassDetailContainer.tsx
  src/components/classDetail/ClassDetailLeft.tsx
  src/components/classDetail/ClassDetailRight.tsx
  src/components/classDetail/ClassImageCarousel.tsx
  src/components/classDetail/ClassSummary.tsx
  src/components/classDetail/CommentsCard.tsx
  src/components/classDetail/CreateComments.tsx
  src/components/classDetail/DetailComments.tsx
  src/components/classDetail/EmblaCarouselArrowButtons.tsx
  src/components/classDetail/EmblaCarouselDotButton.tsx
  src/components/classDetail/MapComponent.tsx
  src/components/classDetail/ShowComments.tsx
  src/components/classDetail/embla.css
  src/components/common/Toastify.tsx
  src/components/listpage/CategoryBtns.tsx
  src/components/main/ClassCard.tsx
  src/components/register/Category.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReserveUserInfo.tsx
  tailwind.config.ts
Labels: enhancement

#228 [Feat] - 클래스 수정 페이지 구현 및 세부사항 수정
  src/app/(clrm)/list/detail/[id]/page.tsx
  src/app/(clrm)/main/page.tsx
  src/app/(clrm)/messages/[[...chatRoomId]]/_components/MessagesPage.tsx
  src/app/(clrm)/register/page.tsx
  src/app/(clrm)/register/registerEditPage/[id]/page.tsx
  src/app/api/reserve/insertNotice.ts
  src/components/common/Toastify.tsx
  src/components/main/emblaCarousel.css
  src/components/register/Category.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassDiff.tsx
  src/components/register/ClassTitleType.tsx
  src/components/register/HashTag.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/SelectTime.tsx
  src/components/register/TotalTime.tsx
  src/types/register.ts
Labels: documentation, enhancement

#232 [Refactor] - 리스트페이지 클래스 필터 반응형,튜터님 피드백 수정,embla css 모듈화
  src/app/(clrm)/list/detail/[id]/page.tsx
  src/app/(clrm)/list/page.tsx
  src/app/(clrm)/main/page.tsx
  src/components/chatRooms/ChatButton.tsx
  src/components/classDetail/ClassImageCarousel.tsx
  src/components/classDetail/CreateComments.tsx
  src/components/classDetail/EmblaCarouselArrowButtons.tsx
  src/components/classDetail/ShowComments.tsx
  src/components/classDetail/embla.module.css
  src/components/common/AlertModal.tsx
  src/components/common/bars/ConvertBtn.tsx
  src/components/common/bars/Header.tsx
  src/components/common/bars/SideBar.tsx
  src/components/listpage/CategoryBtns.tsx
  src/components/listpage/ClassList.tsx
  src/components/listpage/SearchFilter.tsx
  src/components/listpage/listpageBtns.tsx
  src/components/login/LoginState.tsx
  src/components/main/BestClass.tsx
  src/components/main/ClassCard.tsx
  src/components/main/ClassSlick.tsx
  src/components/main/DeadlineClass.tsx
  src/components/main/LatestClass.tsx
  src/components/main/emblaCarousel.module.css
  src/components/mypage/MyPageBtn.tsx
  src/components/register/CreateBtn.tsx
  src/store/classFilterStore.ts
  src/types/classFilter.ts
Labels: enhancement

#243 [Fix] - 헤더 css 오류 수정 , 클래스 디테일 페이지 수정사항 반영 안되는 오류 수정 #239
  package.json
  src/app/(clrm)/list/detail/[id]/page.tsx
  src/app/(clrm)/list/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/classdetail/detailClassInfo.ts
  src/app/api/supabase/supabase.ts
  src/components/classDetail/ClassInfos.tsx
  src/components/common/bars/Header.tsx
  src/components/common/bars/SideBar.tsx
  src/components/common/bars/categories/SearchClass.tsx
  src/components/listpage/ClassList.tsx
  src/components/login/LoginState.tsx
  yarn.lock
Labels: enhancement

#248 [Feat] - 클래스 수정 페이지 일정 구현 및 css 수정
  src/app/(clrm)/register/completedPage/[id]/page.tsx
  src/app/(clrm)/register/page.tsx
  src/app/(clrm)/register/registerEditPage/[id]/page.tsx
  src/components/listpage/CategoryBtns.tsx
  src/components/register/Address.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassDiff.tsx
  src/components/register/ClassTitleType.tsx
  src/components/register/CreateBtn.tsx
  src/components/register/HashTag.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/MinMaxNumber.tsx
  src/components/register/Price.tsx
  src/components/register/SelectTime.tsx
  src/components/register/TotalTime.tsx
Labels: documentation, enhancement

#255 [Feat] 클래스 수정 페이지 날짜, 시간 삭제 기능 구현
  src/app/(clrm)/register/registerEditPage/[id]/page.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/SelectTime.tsx
  src/store/registerScheduleStore.ts
Labels: documentation, enhancement

#256 [Feat] - 메인페이지 footer , 팀 소개 페이지 #247
  package.json
  src/app/(clrm)/bugBusters/page.tsx
  src/app/(clrm)/list/detail/[id]/page.tsx
  src/app/(clrm)/list/page.tsx
  src/app/(clrm)/main/page.tsx
  src/app/(clrm)/page.tsx
  src/app/api/classdetail/detailComment.ts
  src/assets/images/BugBusters.png
  src/assets/images/Group 1791.png
  src/assets/images/Hyangji.png
  src/assets/images/Hyerin.png
  src/assets/images/Hyunjin.png
  src/assets/images/Jiwon.png
  src/assets/images/Miju.png
  src/assets/images/Teawon.png
  src/components/bugBusters/PersonalCard.tsx
  src/components/classDetail/ClassDetailLeft.tsx
  src/components/classDetail/ClassDetailRight.tsx
  src/components/classDetail/ClassImageCarousel.tsx
  src/components/classDetail/ClassSummary.tsx
  src/components/classDetail/CommentsCard.tsx
  src/components/classDetail/DetailComments.tsx
  src/components/classDetail/ShowComments.tsx
  src/components/common/Notification.tsx
  src/components/common/bars/Header.tsx
  src/components/common/bars/categories/SearchClass.tsx
  src/components/main/Banner.tsx
  src/components/main/ChatBubble.tsx
  src/components/main/MainFooter.tsx
  src/components/register/CreateBtn.tsx
  src/types/detailComment.ts
  yarn.lock
Labels: enhancement

#257 [Feat] - 배너 제작 및 세부 수정 #250
  src/app/(clrm)/reserve/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/payment/route.ts
  src/app/layout.tsx
  src/assets/images/Ellipse.png
  src/assets/images/candle.png
  src/assets/images/clRoomTextLogo.png
  src/assets/images/lightPurpleGraphic.svg
  src/assets/images/lightPurpleGraphic2.png
  src/assets/images/orangeStar.png
  src/assets/images/purpleFlower.png
  src/assets/images/soap.png
  src/assets/images/yellowStar.png
  src/assets/images/yellowStarStroke.png
  src/components/classDetail/ClassSummary.tsx
  src/components/classDetail/CommentsCard.tsx
  src/components/classDetail/EmblaCarouselLazyLoadImage.tsx
  src/components/classDetail/MapComponent.tsx
  src/components/classDetail/embla.module.css
  src/components/common/CustomCaption.tsx
  src/components/common/Toastify.tsx
  src/components/main/Banner.tsx
  src/components/reserve/ClassInfo.tsx
  src/components/reserve/DateTimePicker.tsx
  src/components/reserve/ReserveButton.tsx
  src/utils/fonts/PretendardVariable.woff2
  src/utils/fonts/fonts.ts
  tailwind.config.ts
Labels: enhancement

#276 [Feat] - metadata 작성 및 개선
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  src/app/(clrm)/register/completedPage/[id]/page.tsx
  src/app/(clrm)/register/page.tsx
  src/app/(clrm)/register/registerEditPage/[id]/page.tsx
  src/app/(clrm)/reserve/success/[reservationId]/page.tsx
  src/app/api/reserve/insertNotice.ts
  src/components/common/Notification.tsx
  src/components/register/Category.tsx
  src/components/register/ClassContent.tsx
  src/components/register/ClassDiff.tsx
  src/components/register/ClassTitleType.tsx
  src/components/register/HashTag.tsx
  src/components/register/ImageUpload.tsx
  src/components/register/Price.tsx
  src/components/register/SelectTime.tsx
Labels: documentation, enhancement
